version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: fincent-1  
      POSTGRES_USER: "hannasaffi"  
      POSTGRES_PASSWORD: "Owenisoliver18!"  
    ports:
      - "5432:5432"  

volumes:
  postgres_data:
