version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: fincent-1  # Replace 'your_database_name' with the actual DB name
      POSTGRES_USER: "hannasaffi"  # Replace 'your_database_user' with your DB username
      POSTGRES_PASSWORD: "Owenisoliver18!"  # Replace 'your_database_password' with your DB password
    ports:
      - "5432:5432"  # Ensure this line is present to expose the port

volumes:
  postgres_data:
