# Generated by Django 5.1.2 on 2024-11-04 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictedStockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('predicted_close_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
